# Generated by Django 4.1.7 on 2023-02-19 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tecnologia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Vaga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=50, null=True)),
                ('descricao', models.TextField()),
                ('salario', models.FloatField(null=True)),
                ('local', models.CharField(max_length=20)),
                ('quantidade', models.IntegerField()),
                ('contato', models.EmailField(max_length=254)),
                ('tipo_contratacao', models.CharField(choices=[('PJ', 'PJ'), ('CLT', 'CLT')], max_length=3)),
                ('tecnologias', models.ManyToManyField(to='api.tecnologia')),
            ],
        ),
    ]
